[package]
name = "egui_heads_tails"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
eframe = "0.23.0"
egui_extras = { version = "*", features = ["all_loaders"] }
image = { version = "0.24", features = ["jpeg", "png"] }
env_logger = "0.10"

